-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.analisis_demanda
(
    id_adem serial NOT NULL,
    exc_adem double precision,
    con_adem double precision,
    per_adem double precision,
    status boolean NOT NULL DEFAULT true,
    fec_adem date NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    CONSTRAINT analisis_demanda_pkey PRIMARY KEY (id_adem)
);

CREATE TABLE IF NOT EXISTS public.arreglo_de_paneles
(
    id_arr serial NOT NULL,
    ptot_arr double precision NOT NULL DEFAULT 0,
    vmax_arr double precision NOT NULL DEFAULT 0,
    imax_arr double precision NOT NULL DEFAULT 0,
    area_arr double precision NOT NULL DEFAULT 0,
    id_pro integer NOT NULL,
    fil_arr integer NOT NULL,
    col_arr integer NOT NULL,
    efi_arr double precision DEFAULT 0,
    status boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    x_arr double precision NOT NULL DEFAULT 100,
    y_arr double precision NOT NULL DEFAULT 100,
    CONSTRAINT arreglo_de_paneles_pkey PRIMARY KEY (id_arr)
);

CREATE TABLE IF NOT EXISTS public.banco_de_baterias
(
    id_ban serial NOT NULL,
    vol_ban double precision NOT NULL DEFAULT 0,
    cap_ban double precision NOT NULL DEFAULT 0,
    ene_ban double precision NOT NULL DEFAULT 0,
    id_pro integer NOT NULL,
    fil_ban integer NOT NULL,
    col_ban integer NOT NULL,
    dod_ban double precision NOT NULL DEFAULT 60,
    status boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    x_ban double precision NOT NULL DEFAULT 871,
    y_ban double precision NOT NULL DEFAULT 310,
    CONSTRAINT banco_de_baterias_pkey PRIMARY KEY (id_ban)
);

CREATE TABLE IF NOT EXISTS public.bateria
(
    id_bat serial NOT NULL,
    ref_bat character varying(100) COLLATE pg_catalog."default" NOT NULL,
    vol_bat double precision NOT NULL,
    cap_bat double precision NOT NULL,
    ene_bat double precision NOT NULL,
    id_usu integer NOT NULL,
    idu_bat character varying(13) COLLATE pg_catalog."default" NOT NULL,
    status boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    CONSTRAINT bateria_pkey PRIMARY KEY (id_bat)
);

CREATE TABLE IF NOT EXISTS public.carga
(
    tip_car character varying(10) COLLATE pg_catalog."default" NOT NULL,
    id_car serial NOT NULL,
    status boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    CONSTRAINT carga_pkey PRIMARY KEY (id_car)
);

CREATE TABLE IF NOT EXISTS public.dato_demanda
(
    id_dem serial NOT NULL,
    dat_dem double precision NOT NULL,
    status boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL,
    update_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    id_usu integer NOT NULL,
    id_adem integer,
    CONSTRAINT dato_demanda_pkey PRIMARY KEY (id_dem)
);

CREATE TABLE IF NOT EXISTS public.dato_irradiancia
(
    id_irr serial NOT NULL,
    prom_irr double precision NOT NULL,
    max_irr double precision NOT NULL,
    status boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL,
    update_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    ubi_irr character varying(100) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Estación Laboratorio Sede Centro CESMAG'::character varying,
    CONSTRAINT dato_irradiancia_pkey PRIMARY KEY (id_irr),
    CONSTRAINT dato_irradiancia_created_at_key UNIQUE (created_at)
);

CREATE TABLE IF NOT EXISTS public.energia_arreglo
(
    id_ene serial NOT NULL,
    tot_ene double precision NOT NULL,
    id_pro integer NOT NULL,
    id_irr integer NOT NULL,
    efi_ene double precision NOT NULL DEFAULT 0,
    status boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    CONSTRAINT energia_arreglo_pkey PRIMARY KEY (id_ene)
);

CREATE TABLE IF NOT EXISTS public.inversor
(
    id_inv serial NOT NULL,
    ref_inv character varying(100) COLLATE pg_catalog."default" NOT NULL,
    ent_inv integer NOT NULL,
    pmax_inv double precision NOT NULL,
    vme_inv double precision NOT NULL,
    ime_inv double precision NOT NULL,
    vsa_inv double precision NOT NULL,
    ond_inv character varying(7) COLLATE pg_catalog."default" NOT NULL,
    efi_inv double precision NOT NULL,
    id_usu integer NOT NULL,
    idu_inv character varying(13) COLLATE pg_catalog."default" NOT NULL,
    status boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    reg_inv character varying(2) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT inversor_pkey PRIMARY KEY (id_inv)
);

CREATE TABLE IF NOT EXISTS public.panel
(
    id_pan serial NOT NULL,
    ref_pan character varying(100) COLLATE pg_catalog."default" NOT NULL,
    pmax_pan double precision NOT NULL,
    vmp_pan double precision NOT NULL,
    imp_pan double precision NOT NULL,
    voc_pan double precision NOT NULL,
    isc_pan double precision NOT NULL,
    lar_pan double precision NOT NULL,
    anc_pan double precision NOT NULL,
    are_pan double precision NOT NULL,
    den_pan double precision NOT NULL,
    id_usu integer NOT NULL,
    idu_pan character varying(13) COLLATE pg_catalog."default" NOT NULL,
    id_tec integer NOT NULL,
    efi_pan double precision NOT NULL,
    status boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    CONSTRAINT panel_pkey PRIMARY KEY (id_pan)
);

CREATE TABLE IF NOT EXISTS public.paralelo_arreglo
(
    id_parr serial NOT NULL,
    pser_parr double precision NOT NULL DEFAULT 0,
    vser_parr double precision NOT NULL DEFAULT 0,
    iser_parr double precision NOT NULL DEFAULT 0,
    aser_parr double precision NOT NULL DEFAULT 0,
    id_arr integer NOT NULL,
    efi_parr double precision DEFAULT 0,
    status boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    CONSTRAINT paralelo_arreglo_pkey PRIMARY KEY (id_parr)
);

CREATE TABLE IF NOT EXISTS public.paralelo_banco
(
    id_pban serial NOT NULL,
    vser_pban double precision NOT NULL DEFAULT 0,
    cser_pban double precision NOT NULL DEFAULT 0,
    eser_pban double precision NOT NULL DEFAULT 0,
    id_ban integer NOT NULL,
    status boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    CONSTRAINT paralelo_banco_pkey PRIMARY KEY (id_pban)
);

CREATE TABLE IF NOT EXISTS public.proyecto_carga
(
    id_pcar serial NOT NULL,
    pot_pcar double precision NOT NULL DEFAULT 0,
    status boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    id_car integer NOT NULL,
    id_pro integer NOT NULL,
    x_pcar double precision NOT NULL DEFAULT 494,
    y_pcar double precision NOT NULL DEFAULT 20,
    CONSTRAINT proyecto_carga_pkey PRIMARY KEY (id_pcar)
);

CREATE TABLE IF NOT EXISTS public.proyecto_fotovoltaica
(
    id_pro integer NOT NULL DEFAULT nextval('proyecto_id_pro_seq'::regclass),
    nom_pro character varying(100) COLLATE pg_catalog."default" NOT NULL,
    id_usu integer NOT NULL,
    cred_pro character varying(2) COLLATE pg_catalog."default" NOT NULL,
    id_inv integer,
    eje_pro boolean NOT NULL DEFAULT false,
    status boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    id_reg integer,
    xinv_pro double precision NOT NULL DEFAULT 494,
    yinv_pro double precision NOT NULL DEFAULT 116,
    xreg_pro double precision NOT NULL DEFAULT 319,
    yreg_pro double precision NOT NULL DEFAULT 116,
    xred_pro double precision NOT NULL DEFAULT 494,
    yred_pro double precision NOT NULL DEFAULT 340,
    CONSTRAINT proyecto_pkey PRIMARY KEY (id_pro)
);

CREATE TABLE IF NOT EXISTS public.regulador
(
    id_reg integer NOT NULL DEFAULT nextval('bateria_id_bat_seq'::regclass),
    ref_reg character varying(100) COLLATE pg_catalog."default" NOT NULL,
    pot_reg double precision NOT NULL,
    vol_reg double precision NOT NULL,
    cor_reg double precision NOT NULL,
    id_usu integer NOT NULL,
    idu_reg character varying(13) COLLATE pg_catalog."default" NOT NULL,
    status boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    CONSTRAINT regulador_pkey PRIMARY KEY (id_reg)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    id_rol serial NOT NULL,
    tip_rol character varying(30) COLLATE pg_catalog."default" NOT NULL,
    status boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    CONSTRAINT roles_pkey PRIMARY KEY (id_rol)
);

CREATE TABLE IF NOT EXISTS public.serie_arreglo
(
    id_sarr serial NOT NULL,
    id_pan integer,
    id_parr integer NOT NULL,
    status boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    CONSTRAINT serie_arreglo_pkey PRIMARY KEY (id_sarr)
);

CREATE TABLE IF NOT EXISTS public.serie_banco
(
    id_sban serial NOT NULL,
    id_bat integer,
    id_pban integer NOT NULL,
    status boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    CONSTRAINT serie_banco_pkey PRIMARY KEY (id_sban)
);

CREATE TABLE IF NOT EXISTS public.tecnologia_panel
(
    id_tec serial NOT NULL,
    nom_tec character varying(100) COLLATE pg_catalog."default" NOT NULL,
    status boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    CONSTRAINT tecnologia_panel_pkey PRIMARY KEY (id_tec)
);

CREATE TABLE IF NOT EXISTS public.usuario
(
    id_usu serial NOT NULL,
    nom_usu character varying(50) COLLATE pg_catalog."default" NOT NULL,
    ape_usu character varying(50) COLLATE pg_catalog."default" NOT NULL,
    cor_usu character varying(100) COLLATE pg_catalog."default" NOT NULL,
    per_usu character varying(15) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Cliente'::character varying,
    doc_usu character varying(10) COLLATE pg_catalog."default" NOT NULL,
    con_usu character varying(35) COLLATE pg_catalog."default" NOT NULL,
    status boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    id_rol integer NOT NULL DEFAULT 1,
    CONSTRAINT usuario_pkey PRIMARY KEY (id_usu),
    CONSTRAINT usuario_cor_usu_key UNIQUE (cor_usu),
    CONSTRAINT usuario_doc_usu_key UNIQUE (doc_usu)
);

ALTER TABLE IF EXISTS public.arreglo_de_paneles
    ADD CONSTRAINT arreglo_de_paneles_id_pro_fkey FOREIGN KEY (id_pro)
    REFERENCES public.proyecto_fotovoltaica (id_pro) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.banco_de_baterias
    ADD CONSTRAINT banco_de_baterias_id_pro_fkey FOREIGN KEY (id_pro)
    REFERENCES public.proyecto_fotovoltaica (id_pro) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.bateria
    ADD CONSTRAINT bateria_id_usu_fkey FOREIGN KEY (id_usu)
    REFERENCES public.usuario (id_usu) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.dato_demanda
    ADD CONSTRAINT dato_demanda_id_adem_fkey FOREIGN KEY (id_adem)
    REFERENCES public.analisis_demanda (id_adem) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.dato_demanda
    ADD CONSTRAINT dato_demanda_id_usu_fkey FOREIGN KEY (id_usu)
    REFERENCES public.usuario (id_usu) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.energia_arreglo
    ADD CONSTRAINT energia_arreglo_id_irr_fkey FOREIGN KEY (id_irr)
    REFERENCES public.dato_irradiancia (id_irr) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.energia_arreglo
    ADD CONSTRAINT energia_arreglo_id_pro_fkey FOREIGN KEY (id_pro)
    REFERENCES public.proyecto_fotovoltaica (id_pro) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.inversor
    ADD CONSTRAINT inversor_id_usu_fkey FOREIGN KEY (id_usu)
    REFERENCES public.usuario (id_usu) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.panel
    ADD CONSTRAINT panel_id_tec_fkey FOREIGN KEY (id_tec)
    REFERENCES public.tecnologia_panel (id_tec) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.panel
    ADD CONSTRAINT panel_id_usu_fkey FOREIGN KEY (id_usu)
    REFERENCES public.usuario (id_usu) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.paralelo_arreglo
    ADD CONSTRAINT paralelo_arreglo_id_arr_fkey FOREIGN KEY (id_arr)
    REFERENCES public.arreglo_de_paneles (id_arr) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.paralelo_banco
    ADD CONSTRAINT paralelo_banco_id_ban_fkey FOREIGN KEY (id_ban)
    REFERENCES public.banco_de_baterias (id_ban) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.proyecto_carga
    ADD CONSTRAINT proyecto_carga_id_car_fkey FOREIGN KEY (id_car)
    REFERENCES public.carga (id_car) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.proyecto_carga
    ADD CONSTRAINT proyecto_carga_id_pro_fkey FOREIGN KEY (id_pro)
    REFERENCES public.proyecto_fotovoltaica (id_pro) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.proyecto_fotovoltaica
    ADD CONSTRAINT proyecto_id_inv_fkey FOREIGN KEY (id_inv)
    REFERENCES public.inversor (id_inv) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.proyecto_fotovoltaica
    ADD CONSTRAINT proyecto_id_reg_fkey FOREIGN KEY (id_reg)
    REFERENCES public.regulador (id_reg) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.proyecto_fotovoltaica
    ADD CONSTRAINT proyecto_id_usu_fkey FOREIGN KEY (id_usu)
    REFERENCES public.usuario (id_usu) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.regulador
    ADD CONSTRAINT regulador_id_usu_fkey FOREIGN KEY (id_usu)
    REFERENCES public.usuario (id_usu) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.serie_arreglo
    ADD CONSTRAINT serie_arreglo_id_pan_fkey FOREIGN KEY (id_pan)
    REFERENCES public.panel (id_pan) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.serie_arreglo
    ADD CONSTRAINT serie_arreglo_id_parr_fkey FOREIGN KEY (id_parr)
    REFERENCES public.paralelo_arreglo (id_parr) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.serie_banco
    ADD CONSTRAINT serie_banco_id_bat_fkey FOREIGN KEY (id_bat)
    REFERENCES public.bateria (id_bat) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.serie_banco
    ADD CONSTRAINT serie_banco_id_pban_fkey FOREIGN KEY (id_pban)
    REFERENCES public.paralelo_banco (id_pban) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.usuario
    ADD CONSTRAINT usuario_id_rol_fkey FOREIGN KEY (id_rol)
    REFERENCES public.roles (id_rol) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;